### ISSUE TITLE
Flatpak Update Error: Key expired

### ISSUE THREAD

**Issue by Itay080** [andyholmes/valent#741] opened 2024-10-18 12:13 UTC
### Current Behavior

Hi!
Looks like the key for the flatpak has expired so it can't be installed

### Expected Behavior

Keys should be renewed so the flatpak can be installed

### Desktop

GNOME Shell

### Operating System

Debian 12

### Installed from

Nightly Flatpak

### Version

nightly

### Logs

```shell
F: Loading https://valent.andyholmes.ca/repo/summaries/69eb8f9e3b62263580f3ad0a506896a991323e181684c436a6e3cc8cc7f75ebe.idx.sig using curl
F: Received 142 bytes
F: Failed to download optional summary index: Signature made Mon 14 Oct 2024 03:58:53 using EdDSA key ID C1C2E37EA92DAB83
BAD signature from " <valent@andyholmes.ca>"
Key expired Thu 17 Oct 2024 06:33:41
```

**Comment by andyholmes** [comment] 2024-10-18 16:34
Thanks for reporting, I guess I forgot the passkey which is kind of a bummer. I'll see if I can extend the expiry, but otherwise...well I've never done this before with a Flatpak repo :)

**Comment by andyholmes** [comment] 2024-10-19 06:12
Hi, the repository should be fixed now, however you may need to remove/add it again:

```sh
flatpak remote-delete valent-origin
flatpak install https://valent.andyholmes.ca/valent.flatpakref
```

(or just click https://valent.andyholmes.ca/valent.flatpakref after removing the remote)

**Closed** 2024-10-19 06:14 UTC
Labels: bug, whoopsie

**Comment by Lehmanator** [comment] 2025-01-25 11:22
Looks like `aarch64` builds are failing after a deps update. `libical`  failed to build.

https://github.com/andyholmes/valent/actions/runs/12959880143/job/36154266825

Trying to install yields the error:

```sh
$ flatpak remote-delete valent-origin
$ flatpak install https://valent.andyholmes.ca/valent.flatpakref
error: No such ref 'app/ca.andyholmes.Valent/aarch64/master' in remote valent-origin
```

Since you also author the GitHub Action for building and deploying flatpaks, figured I'd let you know in case this is a bug where failed builds (or builds failing for one arch but succeeding for another) causes the latest artifacts to be replaced for all architectures when a build only succeeds for one arch.

**Comment by andyholmes** [comment] 2025-01-26 01:14
Huh, yeah that is not...intended. I noticed the aarch64 job failed, so I gave it a bump it looks like a compiler segfault on aarch64 (yay 😉).

That's definitely unfortunate that the aarch64 build disappears in that case, I've opened https://github.com/andyholmes/flatter/issues/124 to track it. Thanks for the heads up, I haven't been updating Valent on my phone so I wouldn't noticed!

**Comment by teohhanhui** [comment] 2025-02-10 22:34
@andyholmes Could the aarch64 build failure be caused by https://github.com/actions/runner-images/issues/10636? The time frame of the change and the build failure seems to match.

**Comment by andyholmes** [comment] 2025-02-11 21:34
I received an e-mail about a comment on this thread, but it seems to have gotten lost!

In any case, they referred to this issue: https://github.com/actions/runner-images/issues/10636, so I poked around and that does seem to be the problem.

https://github.com/andyholmes/valent/actions/runs/13272932784 is running now, so hopefully that will fix the builds. Thanks for the tips everyone!

**Comment by teohhanhui** [comment] 2025-02-11 21:37
Sorry, I deleted my comment as I think it was (probably) mistaken...

**Comment by teohhanhui** [comment] 2025-02-11 21:45
Also, in the future (when the build has been fixed for the newer toolchain) we won't need QEMU for aarch64, considering https://github.com/orgs/community/discussions/19197#discussioncomment-11859757

**Comment by andyholmes** [comment] 2025-02-11 22:27
Ah okay, I think you were right though. There seems to be a problem with qemu that was pulled into ubuntu-24.04 and we just got hit with it now. It looks like it's past the previous crash, so there should be a new build up soon :)
