### ISSUE TITLE
Clicking "Browse files" not opening nautilus

### ISSUE THREAD

**Issue by LaMbA3** [andyholmes/valent#665] opened 2024-04-22 17:05 UTC
### Current Behavior

When i click on browse files, it opens dialog saying "No apps available"

### Expected Behavior

I expected it to open nautilus

### Desktop

GNOME Shell

### Operating System

Fedora 39

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Screenshots

![Screenshot from 2024-04-22 19-05-54](https://github.com/andyholmes/valent/assets/31123517/ff946130-76dd-4ad1-a8ce-f020e2164ef3)

**Comment by andyholmes** [comment] 2024-04-22 20:29
Sorry accidentally mislabeled, this is actually a duplicate of #597

**Closed by andyholmes** 2024-04-22 20:29 UTC
Labels: duplicate
