### ISSUE TITLE
Only one MPRIS player is exported in Flatpak

### ISSUE THREAD

**Issue by vixalien** [andyholmes/valent#638] opened 2024-03-31 14:01 UTC
### Current Behavior

I have Valent connected to my android phone.

Valent only shows one media player in GNOME calendar popover when I play music on the phone.

For example, you can see in the panel that I only have one player.

![image](https://github.com/andyholmes/valent/assets/37999241/ee0c2757-8b0a-41ef-819c-31148c49a923)

But when I click on that player, you can see multiple players.

![image](https://github.com/andyholmes/valent/assets/37999241/fbfb1bee-3518-4a33-9659-0abfb41e905d)

It seems only the first one is shown as an MPRIS player.

### Expected Behavior

I would expect the 2 players to be visible in the GNOME panel.

### Desktop

GNOME Shell

### Operating System

Alpine

### Installed from

Nightly Flatpak

### Version

nightly

### Devices

KDE Connect (Android)

### Plugins

MPRIS

**Comment by andyholmes** [comment] 2024-03-31 18:38
Yes, that's intentional.

Valent only exports on media player at a time when in a Flatpak, for two reasons:

1. That used to be the "free" permission you got from the Flatpak sandbox. I think that might be slightly different now, but I haven't checked in a while.
2. There are many players with broken behaviour or incorrectly reported by other OS's (e.g. Android). GSConnect employs several extremely flakey heuristics to decide whether a player is real and actually playing, rather than:
   - an audio clip in WebView
   - a browser that leaves a player in an undefined state
   - some sketchy background process of Facebook
   - a player with a 2-second lifetime to play a notification sound

I'm not entirely opposed to changing that behaviour to be configurable, but unlike GSConnect I have zero intention of maintaining bizarre heuristics to handle weird stuff other programs or OS's do :slightly_smiling_face:.

I'd want some good design, UX and testing for that though. I'd like to say *"sure, users can suck it up if their players are broken"*, but that's not how issue trackers work :wink:.

**Comment by vixalien** [comment] 2024-03-31 20:15
Ah I see. The only issue is that for some reason the first player is always called "Google" and it's annoying that I can't see the actual music playing through other apps.

Maybe at least exposing only the latest played source would be better.

**Comment by vixalien** [comment] 2024-03-31 20:15
Ah I see. The only issue is that for some reason the first player is always called "Google" and it's annoying that I can't see the actual music playing through other apps.

Maybe at least exposing only the latest played source would be better.

**Comment by andyholmes** [comment] 2024-03-31 20:46
> Maybe at least exposing only the latest played source would be better.

That should be current result, unless the "Google" player starts first and never stops:

https://github.com/andyholmes/valent/blob/28e59d66ba3821a516a797763c152d03db3f9aa6/src/plugins/mpris/valent-mpris-adapter.c#L63-L85

I'm assuming "Google" is something on an Android phone? This sort of falls under the banner of media players and other OS's doing weird things. I'm assuming that if kdeconnect-android could detect this it wouldn't expose the player at all, but maybe it just needs a hard-coded exception on the app-side.

**Comment by vixalien** [comment] 2024-03-31 21:14
Yup it's probably something on my Android phone. The thing is that I can't see any other player in the media players so I can't close it.

It shows no track playing and no duration

**Comment by andyholmes** [comment] 2024-04-10 05:45
I suppose the exporter could try to prioritize the most recent player to start playing. It occurred to me that how the media keys in GNOME probably work.

It's possible the same situation might happen in reverse, but I've never had the media keys on my laptop act on a player I didn't expect.

**Comment by vixalien** [comment] 2024-04-11 23:53
After some thinking, I think this is the best solution:

> I'm assuming that if kdeconnect-android could detect this it wouldn't expose the player at all, but maybe it just needs a hard-coded exception on the app-side.

The "Google" player is not visible in the Android UI, so it shouldn't be visible in kde connect either.

**Comment by vixalien** [comment] 2024-04-11 23:57
But something that could possibly help is hiding players with a duration of 0. I don't know if that will affect like livestreams, but what I noticed is that the Google player doesn't have a duration or audio position.

This also happens with YouTube when I'm playing Shorts:

![image](https://github.com/andyholmes/valent/assets/37999241/22b068d9-dfb8-42fa-ae6b-c3d82246d0bd)

But still the best soluion would be to fiix that in KDE Connect

**Comment by andyholmes** [comment] 2024-04-12 21:33
> But something that could possibly help is hiding players with a duration of 0. I don't know if that will affect like livestreams, but what I noticed is that the Google player doesn't have a duration or audio position.

Yeah, at least in MPRIS only the [`mpris:track_id` is required](https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html#Mapping:Metadata_Map) (which we don't support yet, I believe). I expect `0` is a pretty common fallback to return if `mpris:length` is missing or for other platforms like Android and Media Session API.

**Comment by andyholmes** [comment] 2024-04-24 03:47
Oops. Sorry, I guess the patch doesn't really close the issue 🙃

**Comment by andyholmes** [comment] 2024-07-15 08:35
Is the correct player now exported, since [0232b87](https://github.com/andyholmes/valent/commit/0232b87829a0cdcdddbf6941193fa2c3412dd1c0)? If so, I'm going to close this as expected behaviour, since there are clearly still broken players out there.

**Comment by vixalien** [comment] 2024-07-15 16:32
Heh not sure. I don't really use Valent anymore.

**Comment by andyholmes** [comment] 2024-07-15 16:53
Fair enough :)

I'll close it up then for now, I might just drop the multi-plexer thing and let the bug reports for broken players flow in :)

**Closed** 2024-07-15 17:08 UTC
Labels: UI/UX

**Comment by vixalien** [comment] 2024-07-15 21:28
> I might just drop the multi-plexer thing

what do you mean?

> I don't really use Valent anymore.

btw this is not because Valent isn't useful. In fact, I'd like to thank you for the app. The only reason I'm not using Valent anymore is because I'm currently on iOS and KDE Connect on iOS is nerfed so it's pointless lol.

**Comment by andyholmes** [comment] 2024-07-15 22:33
> what do you mean?

Right now (when in Flatpak), Valent has a little multi-plexer that swaps in the "most active" player. That's pretty much because there will be reports of broken players being exported, and the easiest way to avoid that is by just exporting one active player.

Playing the game of heuristics (e.g. track length of `0`, missing properties, player name ignore lists, etc) is a burden and causes other problems, so I won't do that again. But I might just drop it and say as much on reports, since those should really be reported as bugs at the source (i.e. player/KDE Connect).

**Comment by vixalien** [comment] 2024-07-15 22:47
I see

> But I might just drop it and say as much on reports, since those should really be reported as bugs at the source

This is the way
